### ISSUE TITLE
Change of section numbers

### ISSUE THREAD

**Issue by jie-dong** [ietf-wg-idr/draft-dt-idr-bgp-autoconf-considerations#5]
Perhaps section 5 "BGP peer Discovery at Layer Three" should be subsection 4.2 under section 4 "Analysis of Candidate Approaches"? 
And 5.1-5.4 be the subsection 4.2.1-4.2.4 of the new subsection 4.2 ?
Then 5.5 and 5.6 be the new subsection 4.3 and 4.4 respectively?

**Comment by jhaas-pfrc** [comment]
I've implemented the renumbering.  I've also chosen to move the link local section prior to Layer 3.
